### ISSUE TITLE
ใช้ slog.Any("error", err) แล้วได้ค่าว่าง

### ISSUE THREAD

**Issue by Waratep** [Sellsuki/sellsuki-go-logger#1]
<img width="392" alt="Screen Shot 2565-10-03 at 16 17 26" src="https://user-images.githubusercontent.com/23360237/193542747-c987e0de-74c8-4072-93cf-36ea60e90d9a.png">

กล่องแดงข้างบนใช้ slog.Any("error", err) 
กล่องแดงข้างล่างใช้ slog.Error(err)

**Comment by SpeedxPz** [comment]
Solved on commit 
https://github.com/Sellsuki/sellsuki-go-logger/commit/d4cce36b1d47338fb4e7d15f4a6f8777c7822a41

Release
https://github.com/Sellsuki/sellsuki-go-logger/releases/tag/v1.0.3
